language: python

jobs:
  include:
    - stage: check
      name: "Syntax validation - Python 3.9"
      python: 3.9
      script:
         - python3 -m compileall -q *

    - stage: build
      name: "Build - Python 3.9"
      python: 3.9
      install:
         # Setup a DIALS installation
         - ./.travis/setup-base

      before_script:
         # Enter DIALS environment, install screen19, and update dispatchers
         - cd $HOME/build_dials/build
         - . setpaths.sh
         - libtbx.pip install -e $HOME/build/xia2/screen19
         - libtbx.configure .

      script:
         # Run the tests
         - cd $HOME/build/xia2/screen19
         - pytest -ra -n auto
         - .travis/check-working-directory-is-clean

      # Assuming you have installed the travis-ci CLI tool, after you
      # create the Github repo and add it to Travis, run the
      # following command to finish PyPI deployment setup:
      # $ travis encrypt --pro --add deploy.password -r xia2/screen19
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: __token__
        password:
          secure: T0QEH1dDT3ZG3Ao+jJUpHCzQpxfBdU2xTExSAkjf4Oc8Dk04nhlVV14TIiMjpqll98MpCKcOEjqcsm2VpuJrP0pzgtzqVXMl3Rsc+pm58PheDuaSgsg+vkV3MbBQOhRYWQLz+0+bjSCRcNTam+B+R1oCcYoI5wpODdHoDSsCwK3QBpk71qLRUQ8c7CT728PSVvBAORiR1y8JVdfIAa6299siiFspCwBT5N3yxqAXDZXZ6FQMIp1AjubGvE4E3K9nARQOhoa2NRvsH1r4i354l0o4PlUzjjogD8/qqX2dBMcd7lExJoIBJLMAEVZ0zKC46pmBI/LX0gczBG3hpgD/WPmBqqhfdzl/tkqKLB+LXP/voJf5rTAw63Rb80ibcCt+7b2IYWvpQx1qXlvQyAHwmmL/2/aX/QJ1HSrZ5Y4DQJtkEKBY+GsyqNxXXqDaQy6AO57Y+SVe7LBZh4Q8J6stoGUeYny7ABJzl+lZbc7w3yUpbF54PnFIcRfA/b9kX3cr2wWeZHR9uYMmsRLwWHOh5+9xqrdzDzxoq28zIiaNrivTRLvzmXocKF5pAHtfcP5oSwnSIy0Ut0QC5e6q05kOPtDc7ew/WIs39ZXpAOm0em+ae7UHYbzcQgqIyG3biSrUrQ+OotCj79ZTLwjdI4x+505AiT799c5ino1jmOKot2w=
        on:
          tags: true
          repo: xia2/screen19

    - name: "Flake8 - Python 3.9"
      python: 3.9
      script: .travis/run-flake8
      if: type = pull_request
